baseURL = "https://aymkh.tn"
languageCode = "en-us"
theme = "digitalgarden"
title = "Aymen Khedhriya"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Stack"
url = "/stack"
weight = 3
[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 2
[[menu.social]]
name = "Email"
url = "mailto:yo@aymkh.tn"
weight = 4
[[menu.social]]
name = "Instagram"
url = "https://instagram.com/__aymkh"
weight = 3
[[menu.social]]
name = "LinkedIn"
url = "https://linkedin.com/in/aymkh"
weight = 2
[[menu.social]]
name = "GitHub"
url = "https://github.com/aymkh"
weight = 1
